### ISSUE TITLE
Draggable bug for you should first drag down then up

### ISSUE THREAD

**Issue by aygunoz** [huhuang03/reorderable_grid_view#57]
Hi Dear,
I am developing the application that is not ready yet. In this time, I wanted to let you know the bug and maybe you could fix it.

1. The bug is when you remove item to directly up, is not working. Firstly you should remove down then scrollable works. 
2. Another problem if there is much item like 15, draggable is not working correctly.
3. Draggable let you out off the scope so you sometimes miss clicks.

I thank you much for such a perfect dependency. It's fixed really big problem with my application. I like to donate you guys in the future. You don't know how much I am appreciated.

https://user-images.githubusercontent.com/74569642/211141443-ad742105-ac2a-4ca4-a681-c4e9a25729f7.mp4

**Comment by huhuang03** [comment]
Hello, thank you for you report.

Which version did you use. maybe you can try newest version `2.2.6-alpha.6`

```
dependencies:
  reorderable_grid_view: ^2.2.6-alpha.6
```

1. The bug is when you remove item to directly up, is not working. Firstly you should remove down then scrollable works.
I can't understand what's this mean, can you provide a demo to reproduct this.

2. Another problem if there is much item like 15, draggable is not working correctly.
Still I can't repdocut, can you provide a demo

3. Draggable let you out off the scope so you sometimes miss clicks.
Draggable let you out off the scope, it's a not fixable fornow, because it use app's `overlay` to drag around. And if I create a new `overlay`, it's need remove and readd entity to update ui, which I can't figure out how to fix.

But `miss click` is what mean.

**Comment by aygunoz** [comment]
Hi,
I am using flutter_reorderable_grid_view: ^3.1.3 right now.
I'll add about miss click video. It's about user experience not about but :) So all fine.

https://user-images.githubusercontent.com/74569642/211161841-aa23499c-bd7d-48fa-8dcc-d5f8dd95d643.mov

**Comment by aygunoz** [comment]
I am getting this error with reorderable_grid_view: ^2.2.6-alpha.6 right now. Do you why there is?
![image](https://user-images.githubusercontent.com/74569642/211167301-c292828a-ab0c-4eea-a7cd-f7a9ed48d6f0.png)

**Comment by aygunoz** [comment]
Also there wasn't this problem with flutter_reorderable_grid_view: ^3.1.3. It's rebuild item that I'am dragging :/

https://user-images.githubusercontent.com/74569642/211167638-1ac84fe8-0fe0-4792-93f8-22726e7e367d.mp4

**Comment by aygunoz** [comment]
I opened clear separate bug report so closed this.
